# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-22 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_available', models.FloatField()),
                ('amount_locked', models.FloatField()),
                ('amount_invested', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('asked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Friends_Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('fk_friends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Friend')),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_loan', models.FloatField()),
                ('amount_interest', models.FloatField()),
                ('state', models.BooleanField(default=False)),
                ('fk_friend_loans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Friends_Loans')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('num', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
                ('fk_friends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Friend')),
                ('fk_loans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Loans')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('num_visit', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('pin', models.CharField(blank=True, max_length=100, null=True)),
                ('img_profile', models.ImageField(blank=True, null=True, upload_to=server.models.Person._path_image)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_request', models.FloatField()),
                ('amount_available', models.FloatField()),
                ('interest', models.FloatField()),
                ('date_return', models.IntegerField()),
                ('date_expiration', models.DateField()),
                ('deadline', models.DateField()),
                ('date_create', models.DateField(auto_now_add=True)),
                ('commentary', models.CharField(max_length=150)),
                ('state', models.BooleanField(default=True)),
                ('fk_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Person')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='fk_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Person'),
        ),
        migrations.AddField(
            model_name='notification',
            name='fk_request_loans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Request_Loans'),
        ),
        migrations.AddField(
            model_name='friends_loans',
            name='fk_request_loans',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='server.Request_Loans'),
        ),
        migrations.AddField(
            model_name='friend',
            name='fk_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='server.Person'),
        ),
        migrations.AddField(
            model_name='friend',
            name='fk_person_friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_friend', to='server.Person'),
        ),
        migrations.AddField(
            model_name='account',
            name='fk_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Person'),
        ),
    ]
